# Generated by Django 3.2.25 on 2024-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblCustomer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerEmailId', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'tblCustomer',
            },
        ),
        migrations.CreateModel(
            name='tblOrder',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.IntegerField()),
                ('ProductIds', models.CharField(max_length=1000)),
                ('Quantity', models.CharField(max_length=1000)),
                ('PaidDenominations', models.CharField(max_length=1000)),
                ('BalanceDenominations', models.CharField(max_length=1000)),
                ('TotalAmountPaid', models.FloatField()),
                ('TotalAmountReturn', models.FloatField()),
                ('OrderDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblOrder',
            },
        ),
        migrations.CreateModel(
            name='tblProduct',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=1000)),
                ('AvailableStock', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('TaxPercentage', models.FloatField()),
            ],
            options={
                'db_table': 'tblProduct',
            },
        ),
    ]
